/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tricongeophysics_FocusDbIO */

#ifndef _Included_com_tricongeophysics_FocusDbIO
#define _Included_com_tricongeophysics_FocusDbIO
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tricongeophysics_FocusDbIO_SDB_NORMAL
#define com_tricongeophysics_FocusDbIO_SDB_NORMAL 0L
#undef com_tricongeophysics_FocusDbIO_SDB_ILATTR
#define com_tricongeophysics_FocusDbIO_SDB_ILATTR 12L
#undef com_tricongeophysics_FocusDbIO_SDB_ILCLASS
#define com_tricongeophysics_FocusDbIO_SDB_ILCLASS 333L
#undef com_tricongeophysics_FocusDbIO_SDB_ILEVENT
#define com_tricongeophysics_FocusDbIO_SDB_ILEVENT 10L
#undef com_tricongeophysics_FocusDbIO_SDB_ILKEY
#define com_tricongeophysics_FocusDbIO_SDB_ILKEY 555L
#undef com_tricongeophysics_FocusDbIO_SDB_ILLINE
#define com_tricongeophysics_FocusDbIO_SDB_ILLINE 6L
#undef com_tricongeophysics_FocusDbIO_SDB_ILMODEL
#define com_tricongeophysics_FocusDbIO_SDB_ILMODEL 8L
#undef com_tricongeophysics_FocusDbIO_SDB_ILPRJTYP
#define com_tricongeophysics_FocusDbIO_SDB_ILPRJTYP 119L
#undef com_tricongeophysics_FocusDbIO_SDB_ILPROJ
#define com_tricongeophysics_FocusDbIO_SDB_ILPROJ 33L
#undef com_tricongeophysics_FocusDbIO_SDB_LCLCLS
#define com_tricongeophysics_FocusDbIO_SDB_LCLCLS 126L
#undef com_tricongeophysics_FocusDbIO_SDB_LCLCONN
#define com_tricongeophysics_FocusDbIO_SDB_LCLCONN 125L
#undef com_tricongeophysics_FocusDbIO_SDB_LENERR
#define com_tricongeophysics_FocusDbIO_SDB_LENERR 888L
#undef com_tricongeophysics_FocusDbIO_SDB_MDLEXIST
#define com_tricongeophysics_FocusDbIO_SDB_MDLEXIST 16L
#undef com_tricongeophysics_FocusDbIO_SDB_MISM
#define com_tricongeophysics_FocusDbIO_SDB_MISM 28L
#undef com_tricongeophysics_FocusDbIO_SDB_NMF
#define com_tricongeophysics_FocusDbIO_SDB_NMF 999L
#undef com_tricongeophysics_FocusDbIO_SDB_NOTFND
#define com_tricongeophysics_FocusDbIO_SDB_NOTFND 444L
#undef com_tricongeophysics_FocusDbIO_SDB_PROT
#define com_tricongeophysics_FocusDbIO_SDB_PROT 222L
#undef com_tricongeophysics_FocusDbIO_SDB_READ
#define com_tricongeophysics_FocusDbIO_SDB_READ 111L
#undef com_tricongeophysics_FocusDbIO_SDB_REMCLS
#define com_tricongeophysics_FocusDbIO_SDB_REMCLS 128L
#undef com_tricongeophysics_FocusDbIO_SDB_REMCONN
#define com_tricongeophysics_FocusDbIO_SDB_REMCONN 127L
/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_initIDs
  (JNIEnv *, jobject);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeInitializeProject
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeInitializeProject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeInitializeProjectWithSurveyRoot
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeInitializeProjectWithSurveyRoot
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeLoadAttr
 * Signature: (Lcom/tricongeophysics/FocusDbAttr;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeLoadAttr
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeLoadAttrNames2
 * Signature: (Lcom/tricongeophysics/TriconGeometry;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeLoadAttrNames2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeLoadAttrNames
 * Signature: (Lcom/tricongeophysics/TriconGeometry;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeLoadAttrNames
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeSaveAttribute
 * Signature: (Lcom/tricongeophysics/FocusDbAttr;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeSaveAttribute
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeGetModel
 * Signature: (Lcom/tricongeophysics/FocusDbModel;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeGetModel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeDeleteModel
 * Signature: (Lcom/tricongeophysics/FocusDbModel;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeDeleteModel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeCreateModel
 * Signature: (Lcom/tricongeophysics/FocusDbModel;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeCreateModel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeExtendModel
 * Signature: (Lcom/tricongeophysics/FocusDbModel;I)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeExtendModel
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeChrPut
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeChrPut
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeChrGet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tricongeophysics_FocusDbIO_nativeChrGet
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeBinGet
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tricongeophysics_FocusDbIO_nativeBinGet
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeBinPut
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeBinPut
  (JNIEnv *, jobject, jstring, jstring, jstring, jintArray);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeAscPut
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_FocusDbIO_nativeAscPut
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_tricongeophysics_FocusDbIO
 * Method:    nativeAscGet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tricongeophysics_FocusDbIO_nativeAscGet
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
