/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tricongeophysics_ParadigmDataSetIO */

#ifndef _Included_com_tricongeophysics_ParadigmDataSetIO
#define _Included_com_tricongeophysics_ParadigmDataSetIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tricongeophysics_ParadigmDataSetIO
 * Method:    nativeInitializeDataSet
 * Signature: (Lcom/tricongeophysics/DataSet;)Lcom/tricongeophysics/DataSet;
 */
JNIEXPORT jobject JNICALL Java_com_tricongeophysics_ParadigmDataSetIO_nativeInitializeDataSet
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tricongeophysics_ParadigmDataSetIO
 * Method:    nativeLoadGatherIDFirstTrace
 * Signature: (ILcom/tricongeophysics/SeismicTrace;)Lcom/tricongeophysics/SeismicTrace;
 */
JNIEXPORT jobject JNICALL Java_com_tricongeophysics_ParadigmDataSetIO_nativeLoadGatherIDFirstTrace
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_tricongeophysics_ParadigmDataSetIO
 * Method:    nativeLoadDataSetFirstTrace
 * Signature: (Lcom/tricongeophysics/SeismicTrace;)Lcom/tricongeophysics/SeismicTrace;
 */
JNIEXPORT jobject JNICALL Java_com_tricongeophysics_ParadigmDataSetIO_nativeLoadDataSetFirstTrace
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tricongeophysics_ParadigmDataSetIO
 * Method:    nativeLoadNextGatherFirstTrace
 * Signature: (Lcom/tricongeophysics/SeismicTrace;)Lcom/tricongeophysics/SeismicTrace;
 */
JNIEXPORT jobject JNICALL Java_com_tricongeophysics_ParadigmDataSetIO_nativeLoadNextGatherFirstTrace
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tricongeophysics_ParadigmDataSetIO
 * Method:    nativeLoadNextTrace
 * Signature: (Lcom/tricongeophysics/SeismicTrace;)Lcom/tricongeophysics/SeismicTrace;
 */
JNIEXPORT jobject JNICALL Java_com_tricongeophysics_ParadigmDataSetIO_nativeLoadNextTrace
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tricongeophysics_ParadigmDataSetIO
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_ParadigmDataSetIO_initIDs
  (JNIEnv *, jobject);

/*
 * Class:     com_tricongeophysics_ParadigmDataSetIO
 * Method:    nativeChangeSortOrder
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tricongeophysics_ParadigmDataSetIO_nativeChangeSortOrder
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
